[2025-01-02T00:06:55.119+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-02T00:06:55.153+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: create_table_dag.create_tables manual__2025-01-01T21:55:28.796834+00:00 [queued]>
[2025-01-02T00:06:55.170+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: create_table_dag.create_tables manual__2025-01-01T21:55:28.796834+00:00 [queued]>
[2025-01-02T00:06:55.171+0000] {taskinstance.py:2866} INFO - Starting attempt 3 of 3
[2025-01-02T00:06:55.195+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): create_tables> on 2025-01-01 21:55:28.796834+00:00
[2025-01-02T00:06:55.209+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=588) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-02T00:06:55.211+0000] {standard_task_runner.py:72} INFO - Started process 589 to run task
[2025-01-02T00:06:55.212+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'create_table_dag', 'create_tables', 'manual__2025-01-01T21:55:28.796834+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/create_table_dag.py', '--cfg-path', '/tmp/tmpxuu9atvz']
[2025-01-02T00:06:55.213+0000] {standard_task_runner.py:105} INFO - Job 45: Subtask create_tables
[2025-01-02T00:06:55.235+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-01-02T00:06:55.318+0000] {task_command.py:467} INFO - Running <TaskInstance: create_table_dag.create_tables manual__2025-01-01T21:55:28.796834+00:00 [running]> on host a26fd2b06b06
[2025-01-02T00:06:55.539+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='aiflow' AIRFLOW_CTX_DAG_ID='create_table_dag' AIRFLOW_CTX_TASK_ID='create_tables' AIRFLOW_CTX_EXECUTION_DATE='2025-01-01T21:55:28.796834+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-01T21:55:28.796834+00:00'
[2025-01-02T00:06:55.541+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-02T00:06:55.588+0000] {utils.py:59} INFO - News sentiment analysis database connection established successfully.
[2025-01-02T00:06:55.590+0000] {create_table_dag.py:25} INFO - Tables created successfully
[2025-01-02T00:06:55.591+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-02T00:06:55.613+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-02T00:06:55.614+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=create_table_dag, task_id=create_tables, run_id=manual__2025-01-01T21:55:28.796834+00:00, execution_date=20250101T215528, start_date=20250102T000655, end_date=20250102T000655
[2025-01-02T00:06:55.671+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-02T00:06:55.717+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-02T00:06:55.720+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
